// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBooking = `-- name: CancelBooking :one
UPDATE bookings
SET status = 'CANCELLED', updated_at = NOW()
WHERE id = $1
RETURNING id, property_id, guest_id, check_in_date, check_out_date, total_guests, nightly_price, total_price, status, created_at, updated_at
`

func (q *Queries) CancelBooking(ctx context.Context, id pgtype.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, cancelBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.GuestID,
		&i.CheckInDate,
		&i.CheckOutDate,
		&i.TotalGuests,
		&i.NightlyPrice,
		&i.TotalPrice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countOverlappingBookings = `-- name: CountOverlappingBookings :one
SELECT COUNT(*) FROM bookings
WHERE property_id = $1
  AND status = 'CONFIRMED'
  AND check_in_date < $2
  AND check_out_date > $3
`

type CountOverlappingBookingsParams struct {
	PropertyID   pgtype.UUID `json:"property_id"`
	CheckOutDate pgtype.Date `json:"check_out_date"`
	CheckInDate  pgtype.Date `json:"check_in_date"`
}

// CountOverlappingBookings counts CONFIRMED reservations on a property whose
// date range collides with [check_in_date, check_out_date). Two half-open date
// ranges overlap if each starts before the other ends; the checkout day is
// free, so back-to-back stays (one guest checks out the day the next checks in)
// do not conflict.
func (q *Queries) CountOverlappingBookings(ctx context.Context, arg CountOverlappingBookingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOverlappingBookings, arg.PropertyID, arg.CheckOutDate, arg.CheckInDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
    property_id, guest_id, check_in_date, check_out_date,
    total_guests, nightly_price, total_price
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
RETURNING id, property_id, guest_id, check_in_date, check_out_date, total_guests, nightly_price, total_price, status, created_at, updated_at
`

type CreateBookingParams struct {
	PropertyID   pgtype.UUID `json:"property_id"`
	GuestID      pgtype.UUID `json:"guest_id"`
	CheckInDate  pgtype.Date `json:"check_in_date"`
	CheckOutDate pgtype.Date `json:"check_out_date"`
	TotalGuests  int32       `json:"total_guests"`
	NightlyPrice int64       `json:"nightly_price"`
	TotalPrice   int64       `json:"total_price"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.PropertyID,
		arg.GuestID,
		arg.CheckInDate,
		arg.CheckOutDate,
		arg.TotalGuests,
		arg.NightlyPrice,
		arg.TotalPrice,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.GuestID,
		&i.CheckInDate,
		&i.CheckOutDate,
		&i.TotalGuests,
		&i.NightlyPrice,
		&i.TotalPrice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, property_id, guest_id, check_in_date, check_out_date, total_guests, nightly_price, total_price, status, created_at, updated_at FROM bookings WHERE id = $1
`

func (q *Queries) GetBookingByID(ctx context.Context, id pgtype.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.GuestID,
		&i.CheckInDate,
		&i.CheckOutDate,
		&i.TotalGuests,
		&i.NightlyPrice,
		&i.TotalPrice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookingsByGuest = `-- name: ListBookingsByGuest :many
SELECT id, property_id, guest_id, check_in_date, check_out_date, total_guests, nightly_price, total_price, status, created_at, updated_at FROM bookings WHERE guest_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListBookingsByGuest(ctx context.Context, guestID pgtype.UUID) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByGuest, guestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.GuestID,
			&i.CheckInDate,
			&i.CheckOutDate,
			&i.TotalGuests,
			&i.NightlyPrice,
			&i.TotalPrice,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
