// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ID           pgtype.UUID        `json:"id"`
	PropertyID   pgtype.UUID        `json:"property_id"`
	GuestID      pgtype.UUID        `json:"guest_id"`
	CheckInDate  pgtype.Date        `json:"check_in_date"`
	CheckOutDate pgtype.Date        `json:"check_out_date"`
	TotalGuests  int32              `json:"total_guests"`
	NightlyPrice int64              `json:"nightly_price"`
	TotalPrice   int64              `json:"total_price"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
