// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, password_hash, full_name)
VALUES ($1, $2, $3, $4)
RETURNING id, full_name, email, is_host, last_login, created_at, updated_at
`

type CreateUserParams struct {
	ID           pgtype.UUID `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	FullName     pgtype.Text `json:"full_name"`
}

type CreateUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	FullName  pgtype.Text        `json:"full_name"`
	Email     string             `json:"email"`
	IsHost    pgtype.Bool        `json:"is_host"`
	LastLogin pgtype.Timestamptz `json:"last_login"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.IsHost,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, full_name, password_hash FROM users WHERE email = $1
`

type FindUserByEmailRow struct {
	ID           pgtype.UUID `json:"id"`
	Email        string      `json:"email"`
	FullName     pgtype.Text `json:"full_name"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (FindUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i FindUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, email, full_name FROM users WHERE id = $1
`

type FindUserByIDRow struct {
	ID       pgtype.UUID `json:"id"`
	Email    string      `json:"email"`
	FullName pgtype.Text `json:"full_name"`
}

func (q *Queries) FindUserByID(ctx context.Context, id pgtype.UUID) (FindUserByIDRow, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i FindUserByIDRow
	err := row.Scan(&i.ID, &i.Email, &i.FullName)
	return i, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, email, password_hash, full_name, is_host, last_login, created_at, updated_at FROM users ORDER BY id
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.IsHost,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastLoginStatus = `-- name: UpdateLastLoginStatus :exec
UPDATE users SET last_login = $1 WHERE id = $2
`

type UpdateLastLoginStatusParams struct {
	LastLogin pgtype.Timestamptz `json:"last_login"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateLastLoginStatus(ctx context.Context, arg UpdateLastLoginStatusParams) error {
	_, err := q.db.Exec(ctx, updateLastLoginStatus, arg.LastLogin, arg.ID)
	return err
}
