// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.6
// source: auth.proto

package authpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Authservice_SendRegistrationOTP_FullMethodName = "/user.Authservice/SendRegistrationOTP"
	Authservice_Register_FullMethodName            = "/user.Authservice/Register"
	Authservice_Login_FullMethodName               = "/user.Authservice/Login"
	Authservice_GetProfile_FullMethodName          = "/user.Authservice/GetProfile"
)

// AuthserviceClient is the client API for Authservice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthserviceClient interface {
	// Public: emails a one-time verification code for registration.
	SendRegistrationOTP(ctx context.Context, in *SendRegistrationOTPRequest, opts ...grpc.CallOption) (*SendRegistrationOTPResponse, error)
	// Public: creates a user (verifying the OTP) and logs them in.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Public: authenticates and returns access + refresh tokens.
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Protected: requires a valid JWT (enforced by Envoy's jwt_authn filter,
	// which forwards the verified identity as x-user-id / x-user-email).
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*UserProfile, error)
}

type authserviceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthserviceClient(cc grpc.ClientConnInterface) AuthserviceClient {
	return &authserviceClient{cc}
}

func (c *authserviceClient) SendRegistrationOTP(ctx context.Context, in *SendRegistrationOTPRequest, opts ...grpc.CallOption) (*SendRegistrationOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendRegistrationOTPResponse)
	err := c.cc.Invoke(ctx, Authservice_SendRegistrationOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authserviceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, Authservice_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authserviceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, Authservice_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authserviceClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*UserProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProfile)
	err := c.cc.Invoke(ctx, Authservice_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthserviceServer is the server API for Authservice service.
// All implementations must embed UnimplementedAuthserviceServer
// for forward compatibility.
type AuthserviceServer interface {
	// Public: emails a one-time verification code for registration.
	SendRegistrationOTP(context.Context, *SendRegistrationOTPRequest) (*SendRegistrationOTPResponse, error)
	// Public: creates a user (verifying the OTP) and logs them in.
	Register(context.Context, *RegisterRequest) (*LoginResponse, error)
	// Public: authenticates and returns access + refresh tokens.
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// Protected: requires a valid JWT (enforced by Envoy's jwt_authn filter,
	// which forwards the verified identity as x-user-id / x-user-email).
	GetProfile(context.Context, *GetProfileRequest) (*UserProfile, error)
	mustEmbedUnimplementedAuthserviceServer()
}

// UnimplementedAuthserviceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthserviceServer struct{}

func (UnimplementedAuthserviceServer) SendRegistrationOTP(context.Context, *SendRegistrationOTPRequest) (*SendRegistrationOTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendRegistrationOTP not implemented")
}
func (UnimplementedAuthserviceServer) Register(context.Context, *RegisterRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAuthserviceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthserviceServer) GetProfile(context.Context, *GetProfileRequest) (*UserProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedAuthserviceServer) mustEmbedUnimplementedAuthserviceServer() {}
func (UnimplementedAuthserviceServer) testEmbeddedByValue()                     {}

// UnsafeAuthserviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthserviceServer will
// result in compilation errors.
type UnsafeAuthserviceServer interface {
	mustEmbedUnimplementedAuthserviceServer()
}

func RegisterAuthserviceServer(s grpc.ServiceRegistrar, srv AuthserviceServer) {
	// If the following call panics, it indicates UnimplementedAuthserviceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Authservice_ServiceDesc, srv)
}

func _Authservice_SendRegistrationOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRegistrationOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthserviceServer).SendRegistrationOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authservice_SendRegistrationOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthserviceServer).SendRegistrationOTP(ctx, req.(*SendRegistrationOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authservice_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthserviceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authservice_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthserviceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authservice_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthserviceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authservice_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthserviceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authservice_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthserviceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authservice_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthserviceServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Authservice_ServiceDesc is the grpc.ServiceDesc for Authservice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Authservice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.Authservice",
	HandlerType: (*AuthserviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRegistrationOTP",
			Handler:    _Authservice_SendRegistrationOTP_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Authservice_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Authservice_Login_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _Authservice_GetProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
